export const causes = [
  'Baptist',
  'Human rights',
  'University education',
  'Transitional mental health services',
  'Rehabilitation of offenders',
  'Family disability resources',
  'Transitional living',
  'Psychology and behavioral science',
  'Chemistry',
  'Rural development',
  'Domestic violence',
  'Genetic conditions and birth defects',
  'Marine science',
  'Protestantism',
  'Orchestral music',
  'Personal services',
  'Environmental justice',
  'Medical support services',
  'Astronomy',
  'Bilingual education',
  'Child Protection',
  'Wildlife biodiversity',
  'Food aid',
  'Endocrine, nutritional and metabolic diseases',
  'Individual liberties',
  'Economic development',
  'Refugee Rights',
  'Agriculture, fishing and forestry',
  'Vocational post-secondary education',
  'Economics for youth',
  'Eye diseases',
  'Dance',
  'Housing for the homeless',
  'Supportive housing',
  'Business education',
  'Pharmacology',
  'Peace and Reconciliation',
  'Golf',
  'Child welfare',
  'Patient-centered care',
  'Family planning',
  'Water sports',
  'Sport',
  'Mobile media',
  'Christianity',
  'Democracy',
  'Child educational development',
  'Managed care',
  'Epidemiology',
  'Historic preservation',
  'Job training',
  'Musculoskeletal diseases',
  'Adult and child mentoring',
  'Libraries',
  'Public housing',
  'Job creation and workforce development',
  'Developmental disability services',
  'Oncology',
  'Environment',
  'Higher education',
  'Sports and recreation',
  'Substance abuse treatment',
  'Out-patient medical care',
  'Academic libraries',
  'Climate change',
  "Alzheimer's Disease and other forms of dementia",
  'Child abuse',
  'Interdisciplinary studies',
  'Natural history museums',
  'Arts administration',
  'Equal opportunity in education',
  'Ice skating',
  'Gender Equality',
  'Museums',
  'Educational exchanges',
  'Child care',
  'Food security',
  'Cycling',
  'Courts',
  'Patient social services',
  'Education services',
  'Lutheranism',
  'Cemeteries and burial services',
  'International relations',
  'Land resources',
  'Arms control',
  'Health care access',
  'Natural resources',
  'Victim aid',
  'Neurology',
  'Zoos',
  'Special needs education',
  'Housing services',
  'Mental health care',
  'Community mental health care',
  'Safe Housing',
  'Diseases and conditions',
  'Employment',
  'Fishing and hunting',
  'Mental and behavioral disorders',
  'Science',
  'Food Security',
  'Rehabilitation',
  'Outdoor sports',
  'Sustainable development',
  'Livestock and ranching',
  'Biomedicine',
  'Organ and tissue banks',
  'Immigrant services',
  'Health care management',
  'Humanities',
  'Farm viability',
  'Sororities and fraternities',
  'Physical anthropology',
  'Cybercrime',
  'Scouting programs',
  'Housing rehabilitation',
  'Communicable disease control',
  'Community service',
  'Leadership development',
  'Cerebral palsy',
  'Film and video',
  'Freedom from slavery',
  'Physical and earth sciences',
  'Voluntarism',
  'Kidney diseases',
  'Organized labor',
  'Sexual abuse',
  'Smoking',
  'Emergency medical services',
  'Reading promotion',
  'Preventive care',
  'Public policy',
  'Heart and circulatory system diseases',
  'Political science',
  'Geology',
  'Philanthropy and public policy',
  'Arts councils',
  'Entrepreneurship',
  'Farmlands',
  'Business promotion',
  'Baseball and softball',
  'Graduate and professional education',
  'Adoption',
  "Women's rights",
  'Camps',
  'Public administration',
  'Mathematics',
  'Family counseling',
  'Legal services',
  'Clean Water',
  'Endangered species protection',
  'European football',
  'Financial services',
  'Job counseling',
  'Aquatic wildlife protection',
  'Adolescent parenting',
  'Disaster relief',
  'Basketball',
  'Vocational education',
  'Fire prevention and control',
  'Elder housing',
  'Biology',
  'Addiction services',
  'E-health',
  'Residential mental health care',
  'Philanthropy',
  'Rights of the aged',
  'Law enforcement',
  'Human services management',
  'Vocational rehabilitation',
  'Mental Health',
  'Wildlife sanctuaries',
  'Senior services',
  'Medical specialties',
  'Islam',
  'Information and communications',
  'Running',
  'Antidiscrimination',
  'Blood banks',
  'Diagnostic imaging',
  'Public health',
  'Wildlife Conservation',
  'Bird preservation',
  'LGBTQ rights',
  'Clubs',
  'Physics',
  'Police agencies',
  'Judaism',
  'Public integrity',
  'Theater',
  'Sustainable Agriculture',
  'Opera',
  'Oceans and coastal waters',
  'Community food systems',
  'Juvenile justice',
  'Community and economic development',
  'International development',
  'Brain and nervous system disorders',
  'Food delivery',
  'Equestrianism',
  'First aid training',
  'Playgrounds',
  'Domesticated animals',
  'Home health care',
  'Health care quality',
  'Hospital care',
  'Senior assisted living',
  'Youth development',
  'Justice rights',
  'LGBTQIA+ Equality',
  'Abuse prevention',
  'Public transportation',
  'Basic and emergency aid',
  'Maternal and perinatal health',
  'Urban development',
  'Television',
  'Paratransit',
  'Human services information',
  'Educational management',
  'Health care financing',
  'Benefits planning',
  'Performing arts',
  'Public utilities',
  'Art conservation',
  'Arts and Culture',
  'Early childhood education',
  'In-home aid and personal assistance',
  'Music',
  'COVID-19',
  'Down syndrome',
  'Hospice care',
  'Rent and mortgage assistance',
  'Agriculture',
  'History museums',
  'Cultural rights',
  'Youth organizing',
  'Human services',
  'Publishing',
  'Plant biodiversity',
  'Energy resources',
  'Pediatrics',
  'Youth services',
  'STEM education',
  'Public affairs',
  'Retirement housing',
  'Architecture',
  'Water resources',
  'Arts services',
  'Ending Human Trafficking',
  'Homeless shelters',
  'Consumer protection',
  'Open data',
  'Community beautification',
  'Social rights',
  'Community recreation',
  'Justice and Human Rights',
  'Thrift shops',
  'In-patient medical care',
  'National security',
  'Arts exchange',
  'Parks',
  'Specialty hospital care',
  'Bicycling and pedestrian-oriented development',
  'Middle school education',
  'Prison alternatives',
  'Group homes',
  'Journalism',
  'Gift distribution',
  'Art museums',
  'Business and industry',
  'Arts and culture',
  'Special population support',
  'Reproductive Health',
  'Ethnic museums',
  'Sheltered workshops',
  'Animal welfare',
  'Ending Abuse',
  'Botanical gardens',
  'Food banks',
  'Molecular biology',
  'Community college education',
  'Computer science',
  'Free goods distribution',
  'Vocal music',
  'Climate Action',
  'Family services',
  'Leukemia',
  'Social sciences',
  'Disasters and emergency management',
  'Cultural awareness',
  'Veterinary medicine',
  'Religion',
  'Adult day care',
  'Nursing care',
  'International economics and trade',
  'Disaster Response',
  "Children's hospital care",
  'Cancers',
  'Public safety',
  'Agricultural education',
  'Surgery',
  'Freedom of religion',
  'Foundations',
  'Olympics',
  'Racial Justice',
  'Autism',
  'Community organizing',
  'Organic farming',
  'Health',
  'Archives and special collections',
  'Community service for youth',
  'Arts education',
  'Nonprofits',
  "Children's museums",
  'Urban planning',
  'Dining services',
  'Community health care',
  'Elementary education',
  'Dental care',
  'Financial counseling',
  'Charter school education',
  'Student services',
  'Technology',
  'Reproductive health care',
  'Undergraduate education',
  'Education',
  'Sports training',
  'Housing for people with disabilities',
  'Economic justice',
  'Ecosystem Restoration',
  'Nursing homes',
  'Diversity and intergroup relations',
  'Pharmacies',
  'Right to free movement and asylum',
  'Engineering',
  'Community improvement',
  'Animal Welfare',
  'Catholicism',
  'Adult education',
  'Independent living for people with disabilities',
  'Arthritis',
  'Advocacy journalism',
  'Health care clinics',
  'Biotechnology',
  'Civic participation',
  'Communication media',
  'Multilateral cooperation',
  'Health insurance',
  'Homeless services',
  'Public finance',
  'Youth mentoring',
  'Reproductive rights',
  'Crisis intervention',
  'Sports',
  'School athletics',
  'Shelter and residential care',
  'Visual arts',
  'Physical Health',
  'Psychiatric care',
  'Goodwill promotion',
  'Secondary education',
  'American football',
  'Pensions',
  'Radio',
  'Festivals',
  'Ethnic and racial minority rights',
  'HIV/AIDS',
  'Combat sports',
  'Unknown or not classified',
  'Housing development',
  'Disability Rights',
  'Winter sports',
  'Health care administration and financing',
  'Elementary and secondary education',
  "Disabled persons' rights",
  'Crime prevention',
  'Aerospace engineering',
  'Domestic violence shelters',
  'Economic Growth',
  'Digital Literacy',
  'Historical activities',
  'Foster care',
  'Gardening',
  'Insurance',
];
