export const countries = [
  'Slovakia',
  'Caribbean Netherlands',
  'Gibraltar',
  'Bailiwick of Guernsey',
  'American Samoa',
  'Finland',
  'Puerto Rico',
  'Armenia',
  'Liberia',
  'Singapore',
  'Montenegro',
  'Palestine',
  'Russia',
  'Oman',
  'Algeria',
  'Cape Verde',
  'Solomon Islands',
  'Iran',
  'Micronesia, Federated States of',
  'Iceland',
  'Norway',
  'Brunei',
  'Kenya',
  'Netherlands Antilles',
  'Peru',
  'Argentina',
  'Bangladesh',
  'Comoros',
  'Angola',
  'Belarus',
  'Austria',
  'Madagascar',
  'Belgium',
  'Ireland',
  'Martinique',
  'Ecuador',
  'Ghana',
  'Jordan',
  'Trinidad and Tobago',
  'Mozambique',
  'Jamaica',
  'Montserrat',
  'Germany',
  'China',
  'Vietnam',
  'South Korea',
  'Greenland',
  'Kosovo',
  'Tonga',
  'Antigua and Barbuda',
  'Suriname',
  'Bailiwick of Jersey',
  'Saint Kitts and Nevis',
  'Pitcairn Islands',
  'Malta',
  'Bahamas, The',
  'Guyana',
  'Turkmenistan',
  'New Zealand',
  'Australia',
  'Cambodia',
  'Israel',
  'Papua New Guinea',
  'Guam',
  'Italy',
  'Georgia',
  'Sri Lanka',
  'Togo',
  'Kuwait',
  'Afghanistan',
  'Libya',
  'TW',
  'Mauritania',
  'Spain',
  'North Macedonia',
  'Latvia',
  'Kyrgyzstan',
  'Tunisia',
  'Hungary',
  'North Korea',
  'Morocco',
  'Portugal',
  'Cyprus',
  'Guinea-Bissau',
  'Slovenia',
  'Greece',
  'Chile',
  'United States',
  'Congo, Republic of the',
  'Ukraine',
  'France',
  'Nigeria',
  'Malawi',
  'Bermuda',
  'Tuvalu',
  'Lithuania',
  'Sao Tome and Principe',
  'El Salvador',
  'Ethiopia',
  'Isle of Man',
  'Tajikistan',
  'Barbados',
  'Bhutan',
  'Azerbaijan',
  'Mauritius',
  'Romania',
  'Sint Maarten',
  'Tanzania, United Republic of',
  'Bahrain',
  'Sweden',
  'Macau',
  'Antarctica',
  'Malaysia',
  'Western Sahara',
  'Bulgaria',
  'Poland',
  'Equatorial Guinea',
  'Myanmar',
  'Gambia, The',
  'Japan',
  'Canada',
  'Haiti',
  'Yemen',
  'Moldova, Republic of',
  'Benin',
  'Croatia',
  'Estonia',
  "Lao People's Democratic Republic",
  'San Marino',
  'Central African Republic',
  'Seychelles',
  'Czech Republic',
  'Nauru',
  'Saudi Arabia',
  'Kazakhstan',
  'Dominican Republic',
  'Senegal',
  'Fiji',
  'New Caledonia',
  'Cura\u00e7ao',
  'Guatemala',
  'India',
  'Grenada',
  'Luxembourg',
  'Brazil',
  'Namibia',
  'South Sudan',
  'Eswatini',
  'United Kingdom',
  'Nepal',
  'Colombia',
  'Liechtenstein',
  'East Timor',
  'USA',
  'Uzbekistan',
  'Cayman Islands',
  'Cuba',
  'Gabon',
  'Albania',
  'Guinea',
  'Cameroon',
  'Eritrea',
  'Chad',
  "C\u00f4te d'Ivoire",
  'Zimbabwe',
  'Belize',
  'Somalia',
  'Northern Mariana Islands',
  'Switzerland',
  'Pakistan',
  'Philippines',
  'Bosnia and Herzegovina',
  'Serbia',
  'Marshall Islands',
  'Nicaragua',
  'Guadeloupe',
  'Burundi',
  'Syrian Arab Republic',
  'Virgin Islands',
  'Costa Rica',
  'Honduras',
  'Dominica',
  'Zambia',
  'Maldives',
  'Panama',
  'Uganda',
  'South Africa',
  'Qatar',
  'Monaco',
  'Turkey',
  'Burkina Faso',
  'French Guiana',
  'Netherlands',
  'Niger',
  'Djibouti',
  'Paraguay',
  'Sudan',
  'Vanuatu',
  'Mongolia',
  'Anguilla',
  'Aruba',
  'Palau',
  'Egypt',
  'Samoa',
  'British Virgin Islands',
  'Iraq',
  'Mali',
  'Saint Lucia',
  'Andorra',
  'Hong Kong SAR',
  'Saint Vincent and the Grenadines',
  'Sierra Leone',
  'Cook Islands',
  'Rwanda',
  'Mexico',
  'Denmark',
  'Uruguay',
  'Lebanon',
  'Kiribati',
  'Turks and Caicos Islands',
  'Congo, Democratic Republic of the',
  'Venezuela',
  'Botswana',
  'French Polynesia',
  'Thailand',
  'Indonesia',
  'United Arab Emirates',
  'Lesotho',
  'Bolivia',
];
